language: node_js
node_js:
  - "6"
before_script:
  - npm install
script: npm run test
sudo: required
dist: trusty
addons:
  chrome: stable
  apt:
	update: true
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  ⋮
