{
  "language": "node_js",
  "sudo": true,
  "node_js": "6",
  "before_install": [
    "npm install"
  ],
  "script": [
    "npm run test"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
