language: node_js
node_js:
  - "6"
before_script:
  - npm install
script: npm run test
sudo: required
dist: trusty
addons:
  chrome: stable
  apt:
    update: true
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
